import { Medication } from '../types';
import { translations } from './translations';

/**
 * Pads single digit numbers to two digits with leading zero
 */
function pad(num: number): string {
  return num < 10 ? `0${num}` : `${num}`;
}

/**
 * Returns formatted local timestamp YYYYMMDDTHHMMSS (floating local time per RFC 5545)
 */
function formatIcsDateTime(date: Date, hours: number, minutes: number): string {
  const y = date.getFullYear();
  const m = pad(date.getMonth() + 1);
  const d = pad(date.getDate());
  const h = pad(hours);
  const min = pad(minutes);
  return `${y}${m}${d}T${h}${min}00`;
}

/**
 * Escapes characters according to RFC 5545 specification
 */
function escapeIcsText(str: string): string {
  if (!str) return '';
  return str
    .replace(/\\/g, '\\\\')
    .replace(/;/g, '\\;')
    .replace(/,/g, '\\,')
    .replace(/\n/g, '\\n');
}

/**
 * Generates an RFC 5545 .ics Calendar file string containing daily recurring events
 * with audible and visual VALARM notifications for all active medications.
 */
export function generateIcsCalendar(
  medications: Medication[],
  patientName: string = 'User',
  language: string = 'en'
): string {
  const activeMeds = medications.filter(m => m.isActive && m.scheduledTimes && m.scheduledTimes.length > 0);
  const t = translations[language] || translations.en;

  const now = new Date();
  const dtstamp = `${now.getUTCFullYear()}${pad(now.getUTCMonth() + 1)}${pad(now.getUTCDate())}T${pad(now.getUTCHours())}${pad(now.getUTCMinutes())}${pad(now.getUTCSeconds())}Z`;

  const lines: string[] = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//MediAlert//Smart Medicine Reminder//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    'X-WR-CALNAME:MediAlert Medication Schedule',
    'X-WR-CALDESC:Daily recurring medication alarms and reminders generated by MediAlert',
    `X-WR-TIMEZONE:${Intl.DateTimeFormat().resolvedOptions().timeZone || 'Asia/Kolkata'}`
  ];

  activeMeds.forEach((med) => {
    const foodGuidance = t.foodConditions[med.foodCondition]?.title || med.foodCondition.replace('_', ' ');

    med.scheduledTimes.forEach((timeStr) => {
      const [h, m] = timeStr.split(':').map(Number);
      const startDateTimeStr = formatIcsDateTime(now, h, m);
      // End 15 minutes after start
      const endM = m + 15;
      const endH = h + Math.floor(endM / 60);
      const endDateTimeStr = formatIcsDateTime(now, endH % 24, endM % 60);

      const uid = `medialert-${med.id}-${pad(h)}${pad(m)}-daily@medialert.app`;

      const summary = `💊 Take ${med.name} (${med.dosage})`;
      const description = [
        `Medicine: ${med.name}`,
        `Dosage: ${med.dosage}`,
        `Type: ${med.type}`,
        `Food Guidance: ${foodGuidance}`,
        `Instructions: ${med.instructions || 'Take as prescribed'}`,
        `Patient: ${patientName}`,
        `Exported via MediAlert Smart Medicine Reminder`
      ].join('\\n');

      lines.push(
        'BEGIN:VEVENT',
        `UID:${uid}`,
        `DTSTAMP:${dtstamp}`,
        `DTSTART:${startDateTimeStr}`,
        `DTEND:${endDateTimeStr}`,
        'RRULE:FREQ=DAILY',
        `SUMMARY:${escapeIcsText(summary)}`,
        `DESCRIPTION:${escapeIcsText(description)}`,
        'STATUS:CONFIRMED',
        'TRANSP:TRANSPARENT', // Doesn't mark the whole time slot as busy in calendars
        // Alarm 1: Ring at the exact scheduled time
        'BEGIN:VALARM',
        'ACTION:DISPLAY',
        `DESCRIPTION:Time to take ${escapeIcsText(med.name)} (${escapeIcsText(med.dosage)})`,
        'TRIGGER:-PT0M',
        'END:VALARM',
        // Alarm 2: 5-minute pre-alert
        'BEGIN:VALARM',
        'ACTION:DISPLAY',
        `DESCRIPTION:Upcoming medicine in 5 minutes: ${escapeIcsText(med.name)}`,
        'TRIGGER:-PT5M',
        'END:VALARM',
        'END:VEVENT'
      );
    });
  });

  lines.push('END:VCALENDAR');
  return lines.join('\r\n');
}

/**
 * Initiates browser download of the generated .ics file
 */
export function downloadIcsFile(
  icsContent: string,
  filename: string = 'medialert-medication-schedule.ics'
): void {
  const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/**
 * Generates direct Google Calendar Web template URL for a single medication dose
 */
export function generateGoogleCalendarEventUrl(
  med: Medication,
  timeStr: string,
  patientName: string = 'User'
): string {
  const [h, m] = timeStr.split(':').map(Number);
  const now = new Date();
  const startStr = formatIcsDateTime(now, h, m);
  const endStr = formatIcsDateTime(now, h, m + 15);

  const title = encodeURIComponent(`💊 Take ${med.name} (${med.dosage})`);
  const details = encodeURIComponent(
    `Medicine: ${med.name}\nDosage: ${med.dosage}\nInstructions: ${med.instructions || 'Take as prescribed'}\nPatient: ${patientName}\nManaged via MediAlert`
  );
  const recur = encodeURIComponent('RRULE:FREQ=DAILY');

  return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${title}&dates=${startStr}/${endStr}&recur=${recur}&details=${details}`;
}

/**
 * Connects directly to Google Account Calendar:
 * 1. Generates RFC 5545 ICS schedule with daily recurring VALARM medication sound alarms.
 * 2. Triggers device calendar download / file open.
 * 3. Opens Google Calendar (https://calendar.google.com/calendar/r) so events are imported/synced to Google account.
 * 4. Returns true on success.
 */
export function connectToGoogleCalendar(
  medications: Medication[],
  patientName: string = 'User',
  language: string = 'en'
): boolean {
  try {
    const ics = generateIcsCalendar(medications, patientName, language);
    downloadIcsFile(ics, 'medialert-google-medication-schedule.ics');

    try {
      window.open('https://calendar.google.com/calendar/r', '_blank');
    } catch {}

    return true;
  } catch (err) {
    console.error('Google calendar connect error:', err);
    return false;
  }
}

